# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Create non-root user
RUN useradd -m -u 1000 botuser && chown -R botuser:botuser /app
USER botuser

# Command to run the application
CMD ["python", "main.py"]

---

# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fargona_jobs_db
    environment:
      POSTGRES_DB: fargona_jobs_bot
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  bot:
    build: .
    container_name: fargona_jobs_bot
    depends_on:
      - postgres
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - DATABASE_URL=postgresql+asyncpg://botuser:your_secure_password@postgres:5432/fargona_jobs_bot
      - SUPER_ADMIN_ID=${SUPER_ADMIN_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: